openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /prices/brand/{brandId}/product/{productId}:
    get:
      tags:
        - prices-controller
      summary: 'Get list of prices given product '
      description: "Given brand id, product id and date get final price"
      operationId: getPricesByDateProductIdBrandId
      parameters:
        - name: brandId
          in: path
          description: Value of the brand identifier
          required: true
          schema:
            type: integer
            format: int32
          example: 1
        - name: productId
          in: path
          description: Value of the product identifier
          required: true
          schema:
            type: integer
            format: int32
          example: 35455
        - name: date
          in: query
          description: "Date: search for given date o if null for current date"
          required: false
          schema:
            type: string
          example: 2020-06-14-15.00.00
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PricesDTO"
components:
  schemas:
    PricesDTO:
      type: object
      properties:
        brandId:
          type: integer
          format: int32
        startDate:
          type: string
        endDate:
          type: string
        priceList:
          type: integer
          format: int32
        productId:
          type: integer
          format: int32
        priority:
          type: integer
          format: int32
        price:
          type: number
        curr:
          type: string