CREATE TABLE PRICES
(
	BRAND_ID   INTEGER,
	START_DATE TIMESTAMP,
	END_DATE   TIMESTAMP,
	PRICE_LIST INTEGER,
	PRODUCT_ID varchar(256),
	PRIORITY   INTEGER,
	PRICE      DECIMAL(10, 2),
	CURR       VARCHAR(3)
);