CREATE TABLE IF NOT EXISTS PRICES
(
	PRICE_LIST INTEGER PRIMARY KEY,
	BRAND_ID   INTEGER,
	START_DATE TIMESTAMP,
	END_DATE   TIMESTAMP,
	PRODUCT_ID varchar(256),
	PRIORITY   INTEGER,
	PRICE      DECIMAL(10, 2),
	CURR       VARCHAR(3)
);